-- ============================================================
-- HR Talent Management System - Setup
-- Account: KMOT_AWS1
-- Database: HR_TALENT_DB
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Dedicated warehouse (XS, auto-suspend 60s)
CREATE WAREHOUSE IF NOT EXISTS HR_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'HR Talent Management dedicated warehouse';

-- Database
CREATE DATABASE IF NOT EXISTS HR_TALENT_DB
  COMMENT = 'HR Talent Management System - Demo Financial Corp';

-- Schema
CREATE SCHEMA IF NOT EXISTS HR_TALENT_DB.HR
  COMMENT = 'HR Talent Management Schema';

USE WAREHOUSE HR_WH;
USE DATABASE HR_TALENT_DB;
USE SCHEMA HR;

-- Stage for Streamlit app files and document uploads
CREATE STAGE IF NOT EXISTS HR_TALENT_DB.HR.HR_STAGE
  COMMENT = 'Stage for Streamlit app files and file uploads';

-- Roles
CREATE ROLE IF NOT EXISTS HR_ADMIN_ROLE;
CREATE ROLE IF NOT EXISTS HR_USER_ROLE;
CREATE ROLE IF NOT EXISTS HR_MANAGER_ROLE;
CREATE ROLE IF NOT EXISTS HR_EMPLOYEE_ROLE;

GRANT ALL ON DATABASE HR_TALENT_DB TO ROLE HR_ADMIN_ROLE;
GRANT ALL ON SCHEMA HR_TALENT_DB.HR TO ROLE HR_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE HR_WH TO ROLE HR_ADMIN_ROLE;
GRANT USAGE ON WAREHOUSE HR_WH TO ROLE HR_USER_ROLE;
GRANT USAGE ON WAREHOUSE HR_WH TO ROLE HR_MANAGER_ROLE;
GRANT USAGE ON WAREHOUSE HR_WH TO ROLE HR_EMPLOYEE_ROLE;

GRANT USAGE ON DATABASE HR_TALENT_DB TO ROLE HR_USER_ROLE;
GRANT USAGE ON SCHEMA HR_TALENT_DB.HR TO ROLE HR_USER_ROLE;

GRANT USAGE ON DATABASE HR_TALENT_DB TO ROLE HR_MANAGER_ROLE;
GRANT USAGE ON SCHEMA HR_TALENT_DB.HR TO ROLE HR_MANAGER_ROLE;

GRANT USAGE ON DATABASE HR_TALENT_DB TO ROLE HR_EMPLOYEE_ROLE;
GRANT USAGE ON SCHEMA HR_TALENT_DB.HR TO ROLE HR_EMPLOYEE_ROLE;

-- Grant roles to ACCOUNTADMIN for testing
GRANT ROLE HR_ADMIN_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE HR_USER_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE HR_MANAGER_ROLE TO ROLE ACCOUNTADMIN;

SELECT 'Setup complete' AS STATUS;
