-- ============================================================
-- HR Talent Management System - Views
-- ============================================================

USE WAREHOUSE HR_WH;
USE DATABASE HR_TALENT_DB;
USE SCHEMA HR;

-- ------------------------------------------------------------
-- V_EMPLOYEE_FULL : Full employee view (all joins)
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW HR.V_EMPLOYEE_FULL AS
SELECT
    e.EMPLOYEE_ID,
    e.EMPLOYEE_NAME,
    e.EMPLOYEE_NAME_KANA,
    e.GENDER,
    e.DATE_OF_BIRTH,
    e.AGE,
    e.HIRE_DATE,
    e.TENURE_YEARS,
    e.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    d.PARENT_ID,
    dp.DEPARTMENT_NAME   AS PARENT_DEPT_NAME,
    e.POSITION_ID,
    p.POSITION_NAME,
    p.IS_MANAGER,
    e.JOB_GRADE,
    e.EMPLOYEE_TYPE,
    e.LOCATION,
    e.EMAIL,
    e.PHONE,
    e.MANAGER_ID,
    m.EMPLOYEE_NAME      AS MANAGER_NAME,
    e.ANNUAL_SALARY,
    e.PERFORMANCE_SCORE,
    e.ENGAGEMENT_SCORE,
    e.PROFILE_SUMMARY,
    e.IS_ACTIVE,
    e.CREATED_AT,
    e.UPDATED_AT,
    -- Aggregated skills
    (
        SELECT LISTAGG(s.SKILL_NAME, ', ') WITHIN GROUP (ORDER BY s.SKILL_NAME)
        FROM HR.EMPLOYEE_SKILLS es2
        JOIN HR.SKILLS s ON es2.SKILL_ID = s.SKILL_ID
        WHERE es2.EMPLOYEE_ID = e.EMPLOYEE_ID
    ) AS SKILLS_TEXT,
    -- Aggregated certifications
    (
        SELECT LISTAGG(c.CERTIFICATION_NAME, ', ') WITHIN GROUP (ORDER BY c.CERTIFICATION_NAME)
        FROM HR.EMPLOYEE_CERTIFICATIONS c
        WHERE c.EMPLOYEE_ID = e.EMPLOYEE_ID
    ) AS CERTIFICATIONS_TEXT
FROM HR.EMPLOYEES e
LEFT JOIN HR.DEPARTMENTS d   ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
LEFT JOIN HR.DEPARTMENTS dp  ON d.PARENT_ID = dp.DEPARTMENT_ID
LEFT JOIN HR.POSITIONS p     ON e.POSITION_ID = p.POSITION_ID
LEFT JOIN HR.EMPLOYEES m     ON e.MANAGER_ID = m.EMPLOYEE_ID;

-- ------------------------------------------------------------
-- V_DEPT_HEADCOUNT : Department headcount summary
-- ------------------------------------------------------------
CREATE OR REPLACE VIEW HR.V_DEPT_HEADCOUNT AS
SELECT
    d.DEPARTMENT_ID,
    d.DEPARTMENT_NAME,
    d.PARENT_ID,
    dp.DEPARTMENT_NAME  AS PARENT_DEPT_NAME,
    d.DEPT_LEVEL,
    COUNT(e.EMPLOYEE_ID) AS HEADCOUNT,
    SUM(CASE WHEN e.GENDER = '男性' THEN 1 ELSE 0 END) AS MALE_COUNT,
    SUM(CASE WHEN e.GENDER = '女性' THEN 1 ELSE 0 END) AS FEMALE_COUNT,
    ROUND(AVG(e.PERFORMANCE_SCORE), 2) AS AVG_PERFORMANCE,
    ROUND(AVG(e.ENGAGEMENT_SCORE), 1)  AS AVG_ENGAGEMENT,
    ROUND(AVG(e.AGE), 1)               AS AVG_AGE
FROM HR.DEPARTMENTS d
LEFT JOIN HR.DEPARTMENTS dp ON d.PARENT_ID = dp.DEPARTMENT_ID
LEFT JOIN HR.EMPLOYEES e ON d.DEPARTMENT_ID = e.DEPARTMENT_ID AND e.IS_ACTIVE = TRUE
GROUP BY d.DEPARTMENT_ID, d.DEPARTMENT_NAME, d.PARENT_ID, dp.DEPARTMENT_NAME, d.DEPT_LEVEL;

-- Grant views
GRANT SELECT ON VIEW HR_TALENT_DB.HR.V_EMPLOYEE_FULL TO ROLE HR_USER_ROLE;
GRANT SELECT ON VIEW HR_TALENT_DB.HR.V_EMPLOYEE_FULL TO ROLE HR_MANAGER_ROLE;
GRANT SELECT ON VIEW HR_TALENT_DB.HR.V_DEPT_HEADCOUNT TO ROLE HR_USER_ROLE;
GRANT SELECT ON VIEW HR_TALENT_DB.HR.V_DEPT_HEADCOUNT TO ROLE HR_MANAGER_ROLE;
GRANT SELECT ON ALL VIEWS IN SCHEMA HR_TALENT_DB.HR TO ROLE HR_ADMIN_ROLE;

SELECT 'Views created successfully' AS STATUS;
