-- ============================================================
-- HR Talent Management System - Cortex Search Service
-- ============================================================
-- NOTE: Cortex Search does not support correlated subqueries
-- with change tracking, so we materialize a flat source table.
-- ============================================================

USE WAREHOUSE HR_WH;
USE DATABASE HR_TALENT_DB;
USE SCHEMA HR;

-- Flat source table (Cortex Search requires simple table, no subqueries)
CREATE OR REPLACE TABLE HR.EMPLOYEE_SEARCH_SOURCE AS
SELECT
  e.EMPLOYEE_ID,
  e.EMPLOYEE_NAME,
  d.DEPARTMENT_NAME,
  p.POSITION_NAME,
  e.JOB_GRADE,
  e.GENDER,
  e.LOCATION,
  e.EMPLOYEE_TYPE,
  e.AGE,
  e.TENURE_YEARS,
  e.PERFORMANCE_SCORE,
  e.ENGAGEMENT_SCORE,
  e.PROFILE_SUMMARY,
  COALESCE(sk.SKILLS_TEXT, '') AS SKILLS_TEXT,
  COALESCE(ct.CERTS_TEXT, '')  AS CERTIFICATIONS_TEXT
FROM HR.EMPLOYEES e
JOIN HR.DEPARTMENTS d ON e.DEPARTMENT_ID = d.DEPARTMENT_ID
JOIN HR.POSITIONS p   ON e.POSITION_ID  = p.POSITION_ID
LEFT JOIN (
  SELECT es.EMPLOYEE_ID,
         LISTAGG(s.SKILL_NAME, ', ') WITHIN GROUP (ORDER BY s.SKILL_NAME) AS SKILLS_TEXT
  FROM HR.EMPLOYEE_SKILLS es
  JOIN HR.SKILLS s ON es.SKILL_ID = s.SKILL_ID
  GROUP BY es.EMPLOYEE_ID
) sk ON sk.EMPLOYEE_ID = e.EMPLOYEE_ID
LEFT JOIN (
  SELECT c.EMPLOYEE_ID,
         LISTAGG(c.CERTIFICATION_NAME, ', ') WITHIN GROUP (ORDER BY c.CERTIFICATION_NAME) AS CERTS_TEXT
  FROM HR.EMPLOYEE_CERTIFICATIONS c
  GROUP BY c.EMPLOYEE_ID
) ct ON ct.EMPLOYEE_ID = e.EMPLOYEE_ID
WHERE e.IS_ACTIVE = TRUE;

-- Create Cortex Search Service on the flat table
CREATE OR REPLACE CORTEX SEARCH SERVICE HR.EMPLOYEE_SEARCH_SERVICE
  ON PROFILE_SUMMARY
  ATTRIBUTES EMPLOYEE_ID, EMPLOYEE_NAME, DEPARTMENT_NAME, POSITION_NAME,
             JOB_GRADE, SKILLS_TEXT, CERTIFICATIONS_TEXT, GENDER,
             LOCATION, EMPLOYEE_TYPE, PERFORMANCE_SCORE, ENGAGEMENT_SCORE,
             AGE, TENURE_YEARS
  WAREHOUSE = HR_WH
  TARGET_LAG = '1 hour'
  COMMENT = 'AI-powered employee talent search service'
  AS (
    SELECT * FROM HR.EMPLOYEE_SEARCH_SOURCE
  );

SELECT 'Cortex Search Service created' AS STATUS;
